unique_ids:
  assets:
    170px-Alfred_Deakin_-_Melhuish.jpg: '1731552967158781516556926.6929'
    download.png: '1731553500928287133181644.6796'
    standard-page.html: DHQO75NKDCVH2DU2G7JO5DOMZKCGWEAA
    theme.css: HPFEERJSRHSDM67OBTESBIMKIVTAH6JE
  forms:
    Form1: BXLM4ZWQDEW5NHCXSNNG7FEVU4T6VYYF
  modules: {}
  scripts: {}
  server_modules: {}
